// Generated by CoffeeScript 1.6.3
var define;

define = (function(root) {
  if (typeof root.define === 'function' && root.define.amd) {
    return define;
  } else {
    return function(factory) {
      var module;
      module = factory();
      root.ribcageGoogleMaps.collections.markersCollection = module;
      root.ribcageGoogleMaps.collections.MarkersCollection = module.Model;
      return root.ribcageGoogleMaps.collectionMixins.MarkersCollection = module.mixin;
    };
  }
})(this);

define(function() {
  var BaseCollection, MarkersCollection, markersCollectionMixin;
  BaseCollection = require('ribcage/collections/base').Collection;
  markersCollectionMixin = {};
  MarkersCollection = BaseCollection.extend(markersCollectionMixin);
  return {
    mixin: markersCollectionMixin,
    Collection: MarkersCollection
  };
});
