// Generated by CoffeeScript 1.6.3
var define;

define = (function(root) {
  var require;
  if (typeof root.define === 'function' && root.define.amd) {
    return define;
  } else {
    require = function(dep) {
      return (function() {
        switch (dep) {
          case 'ribcage/collections/base':
            return root.ribcage.collections.baseCollection;
          default:
            return null;
        }
      })() || (function() {
        throw new Error("Unmet dependency " + dep);
      })();
    };
    return function(factory) {
      var m, r;
      m = factory(require);
      r = root.ribcageGoogleMaps;
      r.collections.markersCollection = m;
      r.collections.MarkersCollection = m.Model;
      return r.collectionMixins.MarkersCollection = m.mixin;
    };
  }
})(this);

define(function(require) {
  var BaseCollection, MarkersCollection, markersCollectionMixin;
  BaseCollection = require('ribcage/collections/base').Collection;
  markersCollectionMixin = {};
  MarkersCollection = BaseCollection.extend(markersCollectionMixin);
  return {
    mixin: markersCollectionMixin,
    Collection: MarkersCollection
  };
});
