// Generated by CoffeeScript 1.6.3
var define;

define = (function(root) {
  if (typeof root.define === 'function' && root.define.amd) {
    return root.define;
  } else {
    return function() {};
  }
})(this);

define(function() {
  return null;
});
