// Generated by CoffeeScript 1.6.3
var define;

define = (function(root) {
  var require;
  if (typeof root.define === 'function' && root.define.amd) {
    return root.define;
  } else {
    require = function(dep) {
      return (function() {
        var _ref, _ref1;
        switch (dep) {
          case 'dahelpers':
            return root.dahelpers;
          case './latlong':
            return (_ref = root.ribcageGoogleMaps) != null ? (_ref1 = _ref.models) != null ? _ref1.latLongModel : void 0 : void 0;
          default:
            return null;
        }
      })() || (function() {
        throw new Error("Unmet dependency " + dep);
      })();
    };
    return function(factory) {
      var module;
      module = factory(require);
      root.ribcageGoogleMaps.models.mapDataModel = module;
      root.ribcageGoogleMaps.models.MapDataModel = module.Model;
      return root.ribcageGoogleMaps.modelMixins.MapDataModel = module.mixin;
    };
  }
})(this);

define(function(require) {
  var MapDataModel, dh, latLongModel, mapDataModelMixin;
  dh = require('dahelpers');
  latLongModel = require('./latlong');
  mapDataModelMixin = {
    defaults: dh.extend({
      heading: 0,
      pitch: 0
    }, latLongModel.mixin.defaults)
  };
  Object.defineProperty(mapDataModelMixin, 'heading', {
    get: function() {
      return this.get('heading');
    },
    set: function(v) {
      return this.set({
        heading: parseFloat(v)
      });
    }
  });
  Object.defineProperty(mapDataModelMixin, 'pitch', {
    get: function() {
      return this.get('pitch');
    },
    set: function(v) {
      return this.set({
        pitch: parseFloat(v)
      });
    }
  });
  MapDataModel = latLongModel.Model.extend(mapDataModelMixin);
  return {
    mixin: mapDataModelMixin,
    Model: MapDataModel
  };
});
