// Generated by CoffeeScript 1.6.3
var define;

define = (function(root) {
  var require;
  if (typeof root.define === 'function' && root.define.amd) {
    return define;
  } else {
    require = function(dep) {
      return (function() {
        var _ref, _ref1;
        switch (dep) {
          case 'dahelpers':
            return root.dahelpers;
          case './latlong':
            return (_ref = root.ribcageGoogleMaps) != null ? (_ref1 = _ref.models) != null ? _ref1.latLongModel : void 0 : void 0;
          default:
            return null;
        }
      })() || (function() {
        throw new Error("Unmet dependency " + dep);
      })();
    };
    return function(factory) {
      var module;
      module = factory(require);
      root.ribcageGoogleMaps.models.markerModel = module;
      root.ribcageGoogleMaps.models.MarkerModel = module.Model;
      return root.ribcageGoogleMaps.modelMixins.MarkerModel = module.mixin;
    };
  }
})(this);

define(function(require) {
  var MarkerModel, dh, latLongModel, mapMarkerModelMixin;
  dh = require('dahelpers');
  latLongModel = require('./latlong');
  mapMarkerModelMixin = {
    defaults: dh.extend({
      title: null,
      info: {}
    }, latLongModel.mixin.defaults)
  };
  MarkerModel = latLongModel.Model.extend(mapMarkerModelMixin);
  return {
    mixin: mapMarkerModelMixin,
    Model: MarkerModel
  };
});
